version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 # conectar el puerto por defeto de mongo (27017) con el del contenedor
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db